browser: chrome

URL:
    ranzhi_URL: http://localhost:8068/ranzhi/www


login:
    root: root
    root_passwd: 123456
    shangwu_user: admin
    shangwu_passwd: admin1
    shouru_user: admin
    shouru_passwd: admin1


log:
    file_name: test1.log
    backup: 5
    console_level: WARNING
    file_level: DEBUG
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

DB:
    host: 192.168.0.211
    port: 3306
    db: openplatform
    user: root
    passwd: openplatform
    charset: utf8
